package edu.capella.mobile.android.utils

/**
 * PreferenceKeys.kt : Emum keys used as a key for SharedPreference
 *
 * @author  :  Kush.pandya
 * @version :  1.0
 * @since   :  10-02-2020
 *
 */
enum class PreferenceKeys {

    KEEP_ME_SIGNED_IN,
    EMAIL,
    //ACCESS_TOKEN,

    CURRENT_ACTIVITY,
    PUSH_NOTIFICATION,
    LOGIN_INFO,
    FIRST_TIME_LOGIN,
    //CURRENT_APP_VERSION,
    FP_ANNOUNCEMENT_DATE,
    FP_LEARNER_FACULTY_DATE,
    FP_INTRUCTOR_FACULTY_DATE,
    FP_INTRUCTOR_FACULTY_READ,
    FP_LEARNER_FACULTY_READ,
    FP_LEARNER_ATTEMP_READ,
    FP_LEARNER_ATTEMP_ID,
    FP_ANNOUNCEMENT_READ,
    FP2_ANNOUNCEMENT_READ,
    FP2_ANNOUNCEMENT_DATE,
    GP1_ANNOUNCEMENT_READ,
    GP1_ANNOUNCEMENT_DATE,
    GP2_ANNOUNCEMENT_READ,
    GP2_ANNOUNCEMENT_DATE,
    CACHED_LOGO_PATH,
    OPENAM_TOKEN,
    MULESOFT_ACCESS_TOKEN,
    IS_MULESOFT_ACCESS_TOKEN_AVAILABLE,
    USER_NAME,
    SECRET,
    LEARNER_PROFILE,
    IS_APP_GONE_OUTSIDE,
    USER_ID,
    COURSE_ROOM_DISCUSSION_LINK,
    PROFILE_ID,
    APP_VERSION,
    VIEW_DESCRIPTION_LINK_PATH,
    ANNOUNCEMENT_LIST,
    SECRET_USER,
    APP_KILLED_FROM_RECENT,
    STARTING_BACKGROUND_TIME,
    VISITED_GRADES_STATUS_HISTORY,
    SELECTED_COURSE_IDENTIFIER,
    CREATE_THREAD_RESTORE,
    IS_EDITED,
    CACHED_COURSE_ROOM_DATA,
    FP_LEARNER_ATTEMP_DATA,
    VISITED_GETTING_STARTED_HISTORY,
}
